### ISSUE TITLE
IllegalArgumentException in Judgment.addReferenceCourtCase during enriching and indexing

### ISSUE THREAD

**Issue by lukdumi** [CeON/saos#959]
06:30:49.275 [http-bio-8080-exec-258] WARN  o.s.web.servlet.PageNotFound - No mapping found for HTTP request with URI [/favicon.ico] in DispatcherServlet with name 'dispatcher'
06:32:23.347 [Thread-26] ERROR o.s.batch.core.step.AbstractStep - Encountered an error executing step judgmentIndexingStep in job TAG_POST_UPLOAD_PROCESSING
java.lang.IllegalArgumentException: null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:111) ~[guava-17.0.jar:na]
	at pl.edu.icm.saos.persistence.model.Judgment.addReferencedCourtCase(Judgment.java:535) ~[saos-persistence-0.9.10.jar:na]
	at pl.edu.icm.saos.enrichment.apply.refcases.ReferencedCourtCasesJudgmentUpdater.addToJudgment(ReferencedCourtCasesJudgmentUpdater.java:32) ~[saos-enrichment-0.9.10.jar:na]
	at pl.edu.icm.saos.enrichment.apply.refcases.ReferencedCourtCasesJudgmentUpdater.addToJudgment(ReferencedCourtCasesJudgmentUpdater.java:16) ~[saos-enrichment-0.9.10.jar:na]
	at pl.edu.icm.saos.enrichment.apply.DefaultEnrichmentTagApplier.applyEnrichmentTag(DefaultEnrichmentTagApplier.java:70) ~[saos-enrichment-0.9.10.jar:na]
	at pl.edu.icm.saos.enrichment.apply.JudgmentEnrichmentService.enrich(JudgmentEnrichmentService.java:123) ~[saos-enrichment-0.9.10.jar:na]
	at pl.edu.icm.saos.enrichment.apply.JudgmentEnrichmentService.enrich(JudgmentEnrichmentService.java:101) ~[saos-enrichment-0.9.10.jar:na]
	at pl.edu.icm.saos.enrichment.apply.JudgmentEnrichmentService.enrich(JudgmentEnrichmentService.java:87) ~[saos-enrichment-0.9.10.jar:na]
	at pl.edu.icm.saos.enrichment.apply.JudgmentEnrichmentService.findOneAndEnrich(JudgmentEnrichmentService.java:58) ~[saos-enrichment-0.9.10.jar:na]
	at pl.edu.icm.saos.search.indexing.JudgmentIndexingReader.read(JudgmentIndexingReader.java:54) ~[saos-search-0.9.10.jar:na]
	at pl.edu.icm.saos.search.indexing.JudgmentIndexingReader.read(JudgmentIndexingReader.java:24) ~[saos-search-0.9.10.jar:na]
	at org.springframework.batch.core.step.item.SimpleChunkProvider.doRead(SimpleChunkProvider.java:91) ~[spring-batch-core-3.0.0.RELEASE.jar:3.0.0.RELEASE]
	at org.springframework.batch.core.step.item.SimpleChunkProvider.read(SimpleChunkProvider.java:155) ~[spring-batch-core-3.0.0.RELEASE.jar:3.0.0.RELEASE]
	at org.springframework.batch.core.step.item.SimpleChunkProvider$1.doInIteration(SimpleChunkProvider.java:114) ~[spring-batch-core-3.0.0.RELEASE.jar:3.0.0.RELEASE]
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:368) ~[spring-batch-infrastructure-3.0.0.RELEASE.jar:3.0.0.RELEASE]
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215) ~[spring-batch-infrastructure-3.0.0.RELEASE.jar:3.0.0.RELEASE]
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144) ~[spring-batch-infrastructure-3.0.0.RELEASE.jar:3.0.0.RELEASE]
	at org.springframework.batch.core.step.item.SimpleChunkProvider.provide(SimpleChunkProvider.java:108) ~[spring-batch-core-3.0.0.RELEASE.jar:3.0.0.RELEASE]
	at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:69) ~[spring-batch-core-3.0.0.RELEASE.jar:3.0.0.RELEASE]
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:402) ~[spring-batch-core-3.0.0.RELEASE.jar:3.0.0.RELEASE]
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:326) ~[spring-batch-core-3.0.0.RELEASE.jar:3.0.0.RELEASE]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) ~[spring-tx-4.0.7.RELEASE.jar:4.0.7.RELEASE]
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:267) ~[spring-batch-core-3.0.0.RELEASE.jar:3.0.0.RELEASE]
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:77) ~[spring-batch-core-3.0.0.RELEASE.jar:3.0.0.RELEASE]
	at org.springframework.batch.repeat.support.TaskExecutorRepeatTemplate$ExecutingRunnable.run(TaskExecutorRepeatTemplate.java:262) ~[spring-batch-infrastructure-3.0.0.RELEASE.jar:3.0.0.RELEASE]
	at org.springframework.core.task.SimpleAsyncTaskExecutor$ConcurrencyThrottlingRunnable.run(SimpleAsyncTaskExecutor.java:251) ~[spring-core-4.0.7.RELEASE.jar:4.0.7.RELEASE]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]

------=_Part_234_1654003793.1464676343363--

**Comment by lukdumi** [comment]
The problem lies in enricher https://github.com/CeON/saos-wf-enrich.
